# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  lighthouse-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Lighthouse CI Action
        uses: treosh/lighthouse-ci-action@v9
        with:
          configPath: './lighthouserc.json'
          temporaryPublicStorage: true
  build-container:
    needs: lighthouse-test
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Buildah Build nginx
      uses: redhat-actions/buildah-build@v2.9
      with:
        image: nginx
        workdir: ./nginx
        dockerfiles: ./Dockerfile

    - name: Buildah Build vph
      # You may pin to the exact commit or the version.
      # uses: redhat-actions/buildah-build@b13805753a7ac93d18d14b22f6ebdf8499a3a95e
      uses: redhat-actions/buildah-build@v2.9
      with:
        image: vph
        dockerfiles: ./Dockerfile

